/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleCalendarCallbackRouteImport } from './routes/google-calendar-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRhythmRouteImport } from './routes/_authenticated/rhythm'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedDreamLifeRouteImport } from './routes/_authenticated/dream-life'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBreaksRouteImport } from './routes/_authenticated/breaks'

const GoogleCalendarCallbackRoute = GoogleCalendarCallbackRouteImport.update({
  id: '/google-calendar-callback',
  path: '/google-calendar-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRhythmRoute = AuthenticatedRhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDreamLifeRoute = AuthenticatedDreamLifeRouteImport.update({
  id: '/dream-life',
  path: '/dream-life',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreaksRoute = AuthenticatedBreaksRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/google-calendar-callback': typeof GoogleCalendarCallbackRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dream-life': typeof AuthenticatedDreamLifeRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rhythm': typeof AuthenticatedRhythmRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/google-calendar-callback': typeof GoogleCalendarCallbackRoute
  '/breaks': typeof AuthenticatedBreaksRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dream-life': typeof AuthenticatedDreamLifeRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rhythm': typeof AuthenticatedRhythmRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/google-calendar-callback': typeof GoogleCalendarCallbackRoute
  '/_authenticated/breaks': typeof AuthenticatedBreaksRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dream-life': typeof AuthenticatedDreamLifeRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/rhythm': typeof AuthenticatedRhythmRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/google-calendar-callback'
    | '/breaks'
    | '/calendar'
    | '/dream-life'
    | '/habits'
    | '/onboarding'
    | '/rhythm'
    | '/settings'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/google-calendar-callback'
    | '/breaks'
    | '/calendar'
    | '/dream-life'
    | '/habits'
    | '/onboarding'
    | '/rhythm'
    | '/settings'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/google-calendar-callback'
    | '/_authenticated/breaks'
    | '/_authenticated/calendar'
    | '/_authenticated/dream-life'
    | '/_authenticated/habits'
    | '/_authenticated/onboarding'
    | '/_authenticated/rhythm'
    | '/_authenticated/settings'
    | '/_authenticated/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GoogleCalendarCallbackRoute: typeof GoogleCalendarCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-calendar-callback': {
      id: '/google-calendar-callback'
      path: '/google-calendar-callback'
      fullPath: '/google-calendar-callback'
      preLoaderRoute: typeof GoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rhythm': {
      id: '/_authenticated/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof AuthenticatedRhythmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dream-life': {
      id: '/_authenticated/dream-life'
      path: '/dream-life'
      fullPath: '/dream-life'
      preLoaderRoute: typeof AuthenticatedDreamLifeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks': {
      id: '/_authenticated/breaks'
      path: '/breaks'
      fullPath: '/breaks'
      preLoaderRoute: typeof AuthenticatedBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBreaksRoute: typeof AuthenticatedBreaksRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDreamLifeRoute: typeof AuthenticatedDreamLifeRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRhythmRoute: typeof AuthenticatedRhythmRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBreaksRoute: AuthenticatedBreaksRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDreamLifeRoute: AuthenticatedDreamLifeRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRhythmRoute: AuthenticatedRhythmRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GoogleCalendarCallbackRoute: GoogleCalendarCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
